const {getAllCategories,addCategory,deleteCategory,updateCategory} = require("../controllers/category.controller");
const express = require("express");
const router = express.Router();
const {authenticate} = require("../midllewares/auth.middleware");
const {authorize} = require("../midllewares/role.middleware");
router.get("/",authenticate,authorize("admin"),getAllCategories);
router.post("/", authenticate, authorize("admin"),addCategory);
router.delete("/:id",authenticate,authorize("admin"),deleteCategory);
router.put("/:id",authenticate,authorize("admin"),updateCategory);
module.exports = router;